spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskmanager}
spring.datasource.username=${DB_USER:taskmanager}
spring.datasource.password=${DB_PASSWORD:taskmanager}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
